### ISSUE TITLE
Update instructions to use the file system

### ISSUE THREAD

**Issue by carlosperate** [microbit-playground/microbit-servo-class#1]
I haven't had a chance to try this yet, but looks like a useful little library!
 Now that the File system is available in micropython a user could add this file and do `from servo import Servo`, which would be quite cool.

**Comment by jezdean** [comment]
I'll try to do that tomorrow.

I do prefer to just cut and paste. It's a lot quicker if I make an error.

**Comment by jezdean** [comment]
Many thanks for your kind words. I hope you find it useful.

I've updated the file.

**Comment by jezdean** [comment]
I did update it. I have no idea where it went!

**Comment by carlosperate** [comment]
Great update, thanks @jezdean!
